version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  test1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello test 1"
  test2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello test 2"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          type: approval
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
